[[:negroid #{:dark-hair :curly-hair}]
 [:negroid #{:dark-hair :curly-hair}]
 [:negroid #{:light-skin :curly-hair}]
 [:mongoloid #{:light-skin :dark-hair :medium-nose}]
 [:mongoloid #{:light-skin :dark-hair :curly-hair :medium-nose}]
 [:mongoloid #{:light-skin}]
 [:europoid #{:light-skin :dark-hair :medium-nose}]
 [:europoid #{:curly-hair :medium-nose}]
 [:europoid #{:light-skin :medium-nose}]]